### ISSUE TITLE
Signature is out of date as of v648.0.6480781

### ISSUE THREAD

**Issue by 5h1b** [7ap/internal-studio-patcher#10]
It seems that 
```rust
const SIGNATURE: &[u8] = &[
    0x80, 0xbe, 0x78, 0x01, 0x00, 0x00, 0x00, 0x74, 0x05, 0xe8,
];
``` 
is now incorrect as of v648.0.6480781

- 5h1b

**Comment by d9no** [comment]
Same issue
0.648.0.6480781

**Comment by adudu21isme** [comment]
Same issue too.
Perhaps provide a way to update the signature when it's modified.

**Comment by ghost** [comment]
What is the new signature?

**Comment by 7ap** [comment]
Thanks for opening an issue. Yes, the signature is out of date as of v648. I'll try to get around to this soon.

**Comment by d9no** [comment]
Ok, thank you!

> Thanks for opening an issue. Yes, the signature is out of date as of v648. I'll try to get around to this soon.

**Comment by T6CR** [comment]
@7ap Is there a way I could possibly find this manually? And also how?

Thanks.

**Comment by MuhXd** [comment]
i have no idea what i'm doing

**Comment by MuhXd** [comment]
![image](https://github.com/user-attachments/assets/60b08a38-546e-4f97-a935-10a79c6078e6)

**Comment by 5h1b** [comment]
> @7ap Is there a way I could possibly find this manually? And also how?
> 
> Thanks.

I would also like for you to tell us about how to find it/look for it

(p.s. i'm talking to @7ap not @T6CR)

**Comment by ghost** [comment]
When will the new version be out?

**Comment by kieldbg** [comment]
@5h1b @Tenandrobilgi @adudu21isme @d9no 👀
![image](https://github.com/user-attachments/assets/4625074f-9f39-4391-9a50-5ac56d546151)

**Comment by stan2474** [comment]
Hello, I am Stan.

As a new contributor, I am working on a fix for this out-of-date signature. It should be out later today.

Best Regards,
Stan.

**Comment by genocydr** [comment]
Is there a way you could provide a guide?

**Comment by adudu21isme** [comment]
> @5h1b @Tenandrobilgi @adudu21isme @d9no 👀 ![image](https://private-user-images.githubusercontent.com/175632974/383402712-4625074f-9f39-4391-9a50-5ac56d546151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MzQwNTIsIm5iZiI6MTczMDkzMzc1MiwicGF0aCI6Ii8xNzU2MzI5NzQvMzgzNDAyNzEyLTQ2MjUwNzRmLTlmMzktNDM5MS05YTUwLTVhYzU2ZDU0NjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNlQyMjU1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTFhMjVmYjkzZjMxODM4ZDJjNjZhYzRkNDA4NDI4MjAxZTk4YjRhNGZiNTBkOWY3ZWE0NmY3ZjQ4YzAzMDNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.LRVdibrAin5N28I1B8U1N9tTb-56IBaaCKRwfVhYZ-Q)

What did you do to enable it? i'd like to know.

**Comment by stan2474** [comment]
Hello, I am Stan.

I have updated the signature. The program should now work.

> Is there a way you could provide a guide?

Yes. I will make a guide on how to update the signature.

Kind regards,
Stan.

**Comment by genocydr** [comment]
> Hello, I am Stan.
> 
> I have updated the signature. The program should now work.
> 
> > Is there a way you could provide a guide?
> 
> Yes. I will make a guide on how to update the signature.
> 
> Kind regards, Stan.

Thank you for updating it stan, and could you please send a link to the guide when you make it.

**Comment by 5h1b** [comment]
I'm closing this issue as it seemed  to have been solved, can't wait for the guide stan!

**Comment by 5h1b** [comment]
> @5h1b @Tenandrobilgi @adudu21isme @d9no 👀 ![image](https://private-user-images.githubusercontent.com/175632974/383402712-4625074f-9f39-4391-9a50-5ac56d546151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTAzMzMsIm5iZiI6MTczMDk1MDAzMywicGF0aCI6Ii8xNzU2MzI5NzQvMzgzNDAyNzEyLTQ2MjUwNzRmLTlmMzktNDM5MS05YTUwLTVhYzU2ZDU0NjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNmNTczM2Q0ZTUyYmFkNjEyNDJjMWNiYmY4OWRkNTFiMzYzMjI1MjkwMDYzOWE3MDM0MzM1ZGQ3NjRlNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FVcsZN3zr4iOU91bgzjHGUviL9mebrsVzcEbkUddv0s)

oh and i would also like to know what is the zliveforbeta channel as i never heard of that, and also why some people that i see with studio internal have there profile set as LuauWebService?

**Comment by 5h1b** [comment]
i did some research and it seems zliveforbeta has been deleted, sad :(

**Comment by stan2474** [comment]
Hello @genocydr, I am Stan.

I have made [the guide](https://github.com/7ap/internal-studio-patcher/wiki/Updating). If any issues arise when following this guide, please let me know.

Cheers,
Stan.

**Comment by 5h1b** [comment]
> Hello @genocydr, I am Stan.
> 
> I have made [the guide](https://github.com/7ap/internal-studio-patcher/wiki/Updating). If any issues arise when following this guide, please let me know.
> 
> Cheers, Stan.

Thank you for the guide, stan!

**Comment by genocydr** [comment]
> Hello @genocydr, I am Stan.
> 
> I have made [the guide](https://github.com/7ap/internal-studio-patcher/wiki/Updating). If any issues arise when following this guide, please let me know.
> 
> Cheers, Stan.

Thank you Stan! I do have a question though: Does this work for other channel builds?

**Comment by stan2474** [comment]
> > Hello @genocydr, I am Stan.
> > I have made [the guide](https://github.com/7ap/internal-studio-patcher/wiki/Updating). If any issues arise when following this guide, please let me know.
> > Cheers, Stan.
> 
> Thank you Stan! I do have a question though: Does this work for other channel builds?

Hello @genocydr, I am Stan.

Yes.

Sincerely,
Stan.

**Comment by kieldbg** [comment]
> > @5h1b @Tenandrobilgi @adudu21isme @d9no 👀 ![image](https://private-user-images.githubusercontent.com/175632974/383402712-4625074f-9f39-4391-9a50-5ac56d546151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTAzMzMsIm5iZiI6MTczMDk1MDAzMywicGF0aCI6Ii8xNzU2MzI5NzQvMzgzNDAyNzEyLTQ2MjUwNzRmLTlmMzktNDM5MS05YTUwLTVhYzU2ZDU0NjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNmNTczM2Q0ZTUyYmFkNjEyNDJjMWNiYmY4OWRkNTFiMzYzMjI1MjkwMDYzOWE3MDM0MzM1ZGQ3NjRlNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FVcsZN3zr4iOU91bgzjHGUviL9mebrsVzcEbkUddv0s)
> 
> oh and i would also like to know what is the zliveforbeta channel as i never heard of that, and also why some people that i see with studio internal have there profile set as LuauWebService?

Who have you seen with the profile LuauWebService? I own the account LuauWebService, lel

**Comment by 5h1b** [comment]
> > > @5h1b @Tenandrobilgi @adudu21isme @d9no 👀 ![image](https://private-user-images.githubusercontent.com/175632974/383402712-4625074f-9f39-4391-9a50-5ac56d546151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTAzMzMsIm5iZiI6MTczMDk1MDAzMywicGF0aCI6Ii8xNzU2MzI5NzQvMzgzNDAyNzEyLTQ2MjUwNzRmLTlmMzktNDM5MS05YTUwLTVhYzU2ZDU0NjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNmNTczM2Q0ZTUyYmFkNjEyNDJjMWNiYmY4OWRkNTFiMzYzMjI1MjkwMDYzOWE3MDM0MzM1ZGQ3NjRlNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FVcsZN3zr4iOU91bgzjHGUviL9mebrsVzcEbkUddv0s)
> > 
> > 
> > oh and i would also like to know what is the zliveforbeta channel as i never heard of that, and also why some people that i see with studio internal have there profile set as LuauWebService?
> 
> Who have you seen with the profile LuauWebService? I own the account LuauWebService, lel

maybe it was your account that posted it on the dev forum, are you dumbprogrammer69?

**Comment by 5h1b** [comment]
> Hello @genocydr, I am Stan.
> 
> I have made [the guide](https://github.com/7ap/internal-studio-patcher/wiki/Updating). If any issues arise when following this guide, please let me know.
> 
> Cheers, Stan.

hi, sorry to ask, but can we have a visual tutorial too, i can't seem to understand how IDA works and get stuck on the first part because it says it can't find "VoiceChatEnableApiSecurityCheck"

**Comment by kieldbg** [comment]
> > > > @5h1b @Tenandrobilgi @adudu21isme @d9no 👀 ![image](https://private-user-images.githubusercontent.com/175632974/383402712-4625074f-9f39-4391-9a50-5ac56d546151.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NTAzMzMsIm5iZiI6MTczMDk1MDAzMywicGF0aCI6Ii8xNzU2MzI5NzQvMzgzNDAyNzEyLTQ2MjUwNzRmLTlmMzktNDM5MS05YTUwLTVhYzU2ZDU0NjE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QwMzI3MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWNmNTczM2Q0ZTUyYmFkNjEyNDJjMWNiYmY4OWRkNTFiMzYzMjI1MjkwMDYzOWE3MDM0MzM1ZGQ3NjRlNzVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FVcsZN3zr4iOU91bgzjHGUviL9mebrsVzcEbkUddv0s)
> > > 
> > > 
> > > oh and i would also like to know what is the zliveforbeta channel as i never heard of that, and also why some people that i see with studio internal have there profile set as LuauWebService?
> > 
> > 
> > Who have you seen with the profile LuauWebService? I own the account LuauWebService, lel
> 
> maybe it was your account that posted it on the dev forum, are you dumbprogrammer69?

I used to own that account. LuauWebService is now my new account, as my girl now owns dumbprogrammer69. But yeah, I posted about Studio Internal in the forum.

**Comment by genocydr** [comment]
> hi, sorry to ask, but can we have a visual tutorial too, i can't seem to understand how IDA works and get stuck on the first part because it says it can't find "VoiceChatEnableApiSecurityCheck"

![image](https://github.com/user-attachments/assets/227a322f-0ab9-42b5-843d-b2bca83f9a38)
You should probably search for it in strings.

**Comment by 5h1b** [comment]
> > hi, sorry to ask, but can we have a visual tutorial too, i can't seem to understand how IDA works and get stuck on the first part because it says it can't find "VoiceChatEnableApiSecurityCheck"
> 
> ![image](https://private-user-images.githubusercontent.com/121210981/384636758-227a322f-0ab9-42b5-843d-b2bca83f9a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDQ4NjMsIm5iZiI6MTczMTIwNDU2MywicGF0aCI6Ii8xMjEyMTA5ODEvMzg0NjM2NzU4LTIyN2EzMjJmLTBhYjktNDJiNS04NDNkLWIyYmNhODNmOWEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMjA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTNmMzQ3NzFjNTkwZWNiZWExNTg4ZTcyM2Y3NDJmNTU5Mjc5Y2NiZmIwYzY4Y2ZmOTI3OWM0NzAxZjQ0OGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pczCsGfH4SLxxuTsTjxqIXnhkn70XckBsG7X9HQ68h8) You should probably search for it in strings.

i was just pressing search, sorry i'm new to this stuff

**Comment by 5h1b** [comment]
> > > hi, sorry to ask, but can we have a visual tutorial too, i can't seem to understand how IDA works and get stuck on the first part because it says it can't find "VoiceChatEnableApiSecurityCheck"
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/121210981/384636758-227a322f-0ab9-42b5-843d-b2bca83f9a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMDQ4NjMsIm5iZiI6MTczMTIwNDU2MywicGF0aCI6Ii8xMjEyMTA5ODEvMzg0NjM2NzU4LTIyN2EzMjJmLTBhYjktNDJiNS04NDNkLWIyYmNhODNmOWEzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQwMjA5MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOTNmMzQ3NzFjNTkwZWNiZWExNTg4ZTcyM2Y3NDJmNTU5Mjc5Y2NiZmIwYzY4Y2ZmOTI3OWM0NzAxZjQ0OGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pczCsGfH4SLxxuTsTjxqIXnhkn70XckBsG7X9HQ68h8) You should probably search for it in strings.
> 
> i was just pressing search, sorry i'm new to this stuff

again i'm am stuck, so sorry for taking up your time, the "jump to xref" is disabled for some reason

**Comment by 5h1b** [comment]
i was able to find out how todo it, but i think i did something wrong, all i got was "movups  xmm0, cs:xmmword_1476177F8"

**Comment by genocydr** [comment]
> i was able to find out how todo it, but i think i did something wrong, all i got was "movups xmm0, cs:xmmword_1476177F8"

I'll try and help once I am able to, but at the moment I'm busy.

Do you have discord? I want to be able to contact you faster using discord if that's fine with you.

**Comment by 5h1b** [comment]
> > i was able to find out how todo it, but i think i did something wrong, all i got was "movups xmm0, cs:xmmword_1476177F8"
> 
> I'll try and help once I am able to, but at the moment I'm busy.
> 
> Do you have discord? I want to be able to contact you faster using discord if that's fine with you.

Ya, if it ok with you, can you send me your discord?

**Comment by genocydr** [comment]
> Ya, if it ok with you, can you send me your discord?

genocydr
