### ISSUE TITLE
Not working [ v0.650.0.6500743 / version-0fe66fbb77d84a42 ]

### ISSUE THREAD

**Issue by SatlyBPro** [7ap/internal-studio-patcher#11]
Signature is outdated and the patcher doesn't work for v0.650.0.6500743 (which is version-0fe66fbb77d84a42).

**Comment by d9no** [comment]
Same issue. Not sure why they closed the other thread :/

0.650.0.6500743

**Comment by d9no** [comment]
Hey, I just downloaded the recent release and it works for me. Can you try again?

**Comment by SatlyBPro** [comment]
Never mind, it was just broken a bit.
