### ISSUE TITLE
"Could not find signature." error when patching

### ISSUE THREAD

**Issue by alpharetzy** [7ap/internal-studio-patcher#3]
when trying to patch Studio, this happens;
```
thread 'main' panicked at src/main.rs:31:10:
Could not find signature.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
What am i facing?

**Comment by 7ap** [comment]
Hi, it works as of the current update. Perhaps you've already ran it and the patcher can no longer find the bytes needed to patch it, as it's already been patched? Try re-launching Studio.

**Comment by alpharetzy** [comment]
> Hi, it works as of the current update. Perhaps you've already ran it and the patcher can no longer find the bytes needed to patch it, as it's already been patched? Try re-launching Studio.

then what are the usage instructions?
