### ISSUE TITLE
"Could not find signature." when trying to patch roblox studio Version 0.626.1.6260363 (Aka latest)

### ISSUE THREAD

**Issue by VAr46** [7ap/internal-studio-patcher#4]
When i try to patch the latest version of studio i get this error

thread 'main' panicked at src\main.rs:31:10:
Could not find signature.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

If you're wondering i reinstalled studio and still got the error.

**Comment by VAr46** [comment]
The patcher only works with Version 0.625.0.6250509 and earlier.

**Comment by diamond3500** [comment]
yeah the signature seems to have changed i tried looking for it manually

**Comment by Hylician** [comment]
const SIGNATURE: &[u8] = &[
    0x41, 0x38, 0x9e, 0x78, 0x01, 0x00, 0x00, 0x74, 0x05, 0xe8,
];

#[rustfmt::skip]
const PATCH: &[u8] = &[
    0x41, 0x38, 0x9e, 0x78, 0x01, 0x00, 0x00, 0x90, 0x90, 0xe8
];

**Comment by 7ap** [comment]
Thanks, @Hylician - would you mind submitting a pull request?

**Comment by 7ap** [comment]
Fixed with #5.
