### ISSUE TITLE
Patcher no longer works as intended

### ISSUE THREAD

**Issue by d9no** [7ap/internal-studio-patcher#8]
Had no issues with patcher up until studio's update today, September 4th. I believe that the signature must've been changed.

Studio Version 0.641.0.6410737

**Comment by 7ap** [comment]
Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

**Comment by d9no** [comment]
Great, thank you

**Comment by bluepilledgreat** [comment]
> Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

you

**Comment by uhKenobi** [comment]
> Thanks for opening an issue. Yes, the signature is out of date as of v641. I'll look into this tomorrow.

😭

**Comment by 7ap** [comment]
Pushed a fix.

Before I create a release, I would want a few other people to confirm it works for them.

**Comment by spidercraft** [comment]
uuh, can you give me the link to it

**Comment by d9no** [comment]
> Pushed a fix.
> 
> Before I create a release, I would want a few other people to confirm it works for them.

Is there a compilation? Would be happy to confirm if compiled 😅

**Comment by 7ap** [comment]
Confirmed with a few friends, seems to be good. Download the binary for the latest release [here](https://github.com/7ap/internal-studio-patcher/releases/latest).
