### ISSUE TITLE
Not changing permission level

### ISSUE THREAD

**Issue by zxcvbnmasdf992** [7ap/internal-studio-patcher#9]
I run the program then open studio and create a new baseplate, i run printidentity() and it says 4

**Comment by 7ap** [comment]
The program only grants internal permission, this is intended behavior.

Though, internal permission grants you the ability to pick your command bar's identity by setting an option in the settings menu somewhere. Ensure you see "Roblox Internal" in yellow at the top right and look through Studio's settings.

**Comment by zxcvbnmasdf992** [comment]
I guess I wasn't looking hard enough. Thanks
